/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;
import java.awt.event.WindowEvent;

/**
 * @author pc
 */
public class TaiKhoanGUI extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JToggleButton btnHienMatKhau;
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JButton btnXacNhanDoiMatKhau;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialogQuenMatKhau;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDMaOTP;
    private javax.swing.JTextField txtIDMatKhauMoi;
    private javax.swing.JTextField txtIDTaiKhoan;
    private javax.swing.JTextField txtIDXacNhanMatKhauMoi;
    private javax.swing.JPasswordField txtMatKhau;
    /**
     * Creates new form TaiKhoanGUI
     */
    public TaiKhoanGUI() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println("Look and Feel not set");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new TaiKhoanGUI();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogQuenMatKhau = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDTaiKhoan = new javax.swing.JTextField();
        txtIDMatKhauMoi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtIDXacNhanMatKhauMoi = new javax.swing.JTextField();
        txtIDMaOTP = new javax.swing.JTextField();
        btnXacNhanDoiMatKhau = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnQuenMatKhau = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        btnHienMatKhau = new javax.swing.JToggleButton();

        jDialogQuenMatKhau.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Quên mật khẩu");
        jPanel8.add(jLabel8);

        jLabel9.setText("ID tài khoản");

        jLabel10.setText("Mật khẩu mới");

        jLabel11.setText("Mã OTP");

        jLabel19.setText("Xác nhận mật khẩu mới");

        btnXacNhanDoiMatKhau.setText("Xác nhận đổi mật khẩu");
        btnXacNhanDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogQuenMatKhauLayout = new javax.swing.GroupLayout(jDialogQuenMatKhau.getContentPane());
        jDialogQuenMatKhau.getContentPane().setLayout(jDialogQuenMatKhauLayout);
        jDialogQuenMatKhauLayout.setHorizontalGroup(
                jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogQuenMatKhauLayout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(btnXacNhanDoiMatKhau)
                                .addContainerGap(233, Short.MAX_VALUE))
                        .addGroup(jDialogQuenMatKhauLayout.createSequentialGroup()
                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogQuenMatKhauLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jDialogQuenMatKhauLayout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(47, 47, 47)
                                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtIDMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                                        .addComponent(txtIDTaiKhoan)
                                                        .addComponent(txtIDXacNhanMatKhauMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                                        .addComponent(txtIDMaOTP, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jDialogQuenMatKhauLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jDialogQuenMatKhauLayout.setVerticalGroup(
                jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogQuenMatKhauLayout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIDTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(21, 21, 21)
                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIDMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIDXacNhanMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jDialogQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIDMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addGap(40, 40, 40)
                                .addComponent(btnXacNhanDoiMatKhau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        jButton2.setText("jButton2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ID:");

        jLabel3.setText("Mật khẩu:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("TRÍ SÁCH");

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/library.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("QUẢN LÝ THƯ VIỆN");

        btnQuenMatKhau.setText("Quên mật khẩu");
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });

        btnHienMatKhau.setBackground(new java.awt.Color(242, 242, 242));
        btnHienMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show-password-eye.png"))); // NOI18N
        btnHienMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jLabel6))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(63, 63, 63)
                                                                .addComponent(jLabel4))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                                                        .addComponent(txtMatKhau))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnHienMatKhau))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(btnDangNhap)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnQuenMatKhau)))
                                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnHienMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDangNhap)
                                        .addComponent(btnQuenMatKhau))
                                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (txtID.getText().isEmpty() || txtMatKhau.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập thiếu ID hoặc mật khẩu");
            return;
        }
        int id = Integer.parseInt(txtID.getText());
        String password = String.valueOf(txtMatKhau.getPassword());
        NhanVienBUS nhanVienBUS = new NhanVienBUS();
        boolean result = nhanVienBUS.dangNhap(id, password);
        if (!result) {
            JOptionPane.showMessageDialog(this, "ID hoặc mật khẩu không đúng");
            return;
        }
        NhanVienDTO nvDangNhap = nhanVienBUS.findOne(id);

        if (nvDangNhap.getTinhTrangLamViec() == NhanVienDTO.TinhTrangLamViec.NGHI_VIEC) {
            JOptionPane.showMessageDialog(this, "Không thể đăng nhập vì nhân viên đã nghỉ việc");
            return;
        }

        BaseUI BaseUI = new BaseUI(nvDangNhap);
        BaseUI.setVisible(true);
        BaseUI.setLocationRelativeTo(null);
        BaseUI.setTitle("Xin chào " + nvDangNhap.getHoTen_NV());
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
        jDialogQuenMatKhau.setVisible(true);
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    private void btnXacNhanDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDoiMatKhauActionPerformed
        // check text fields
        if (txtIDTaiKhoan.getText().isEmpty() || txtIDMatKhauMoi.getText().isEmpty() || txtIDXacNhanMatKhauMoi.getText().isEmpty() || txtIDMaOTP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập thiếu thông tin");
            return;
        }

        // check if id is valid
        int idTaiKhoan = Integer.parseInt(txtIDTaiKhoan.getText());
        NhanVienBUS nhanVienBUS = new NhanVienBUS();
        NhanVienDTO nhanVienDTO = nhanVienBUS.findOne(idTaiKhoan);
        if (nhanVienDTO == null) {
            JOptionPane.showMessageDialog(this, "ID không tồn tại");
            return;
        }

        // check if new password and confirm password match
        if (!txtIDMatKhauMoi.getText().equals(txtIDXacNhanMatKhauMoi.getText())) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới không khớp");
            return;
        }

        // check if OTP is correct
        int id = Integer.parseInt(txtIDTaiKhoan.getText());
        String otp = txtIDMaOTP.getText();
        boolean result = nhanVienBUS.checkOTP(id, otp);
        if (!result) {
            JOptionPane.showMessageDialog(this, "Mã OTP không đúng");
            return;
        }
        // update password
        String newPassword = txtIDMatKhauMoi.getText();
        boolean updateResult = nhanVienBUS.updatePassword(id, newPassword);
        if (!updateResult) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra");
            return;
        }
        JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
        jDialogQuenMatKhau.dispatchEvent(new WindowEvent(jDialogQuenMatKhau, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnXacNhanDoiMatKhauActionPerformed

    private void btnHienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienMatKhauActionPerformed
        Icon iconOn = new ImageIcon(getClass().getResource("/images/show-password-eye.png"));   // Icon khi nút được bật
        Icon iconOff = new ImageIcon(getClass().getResource("/images/hidden-password-eye.png")); // Icon khi nút tắt
        if (btnHienMatKhau.isSelected()) {
            btnHienMatKhau.setIcon(iconOn); // Đặt icon khi nút bật
            txtMatKhau.setEchoChar('*');
        } else {
            btnHienMatKhau.setIcon(iconOff); // Đặt icon khi nút tắt
            txtMatKhau.setEchoChar((char)0);
        }
    }//GEN-LAST:event_btnHienMatKhauActionPerformed
    // End of variables declaration//GEN-END:variables
}
